// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _10_Code_first.Data;

#nullable disable

namespace _10_Code_first.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251208024906_add-office-entity")]
    partial class addofficeentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_10_Code_first.Entites.Course", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<decimal>("Price")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.ToTable("Courses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseName = "Mathmatics",
                            Price = 1000m
                        },
                        new
                        {
                            Id = 2,
                            CourseName = "Physics",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 3,
                            CourseName = "Chemistry",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 4,
                            CourseName = "Biology",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 5,
                            CourseName = "CS-50",
                            Price = 3000m
                        });
                });

            modelBuilder.Entity("_10_Code_first.Entites.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<int?>("OfficeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId")
                        .IsUnique()
                        .HasFilter("[OfficeId] IS NOT NULL");

                    b.ToTable("Instructors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Ahmed",
                            LastName = "Abdullah",
                            OfficeId = 1
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Yasmeen",
                            LastName = "Yasmeen",
                            OfficeId = 2
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Khalid",
                            LastName = "Hassan",
                            OfficeId = 3
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Nadia",
                            LastName = "Ali",
                            OfficeId = 4
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Ahmed",
                            LastName = "Abdallah",
                            OfficeId = 5
                        });
                });

            modelBuilder.Entity("_10_Code_first.Entites.Office", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("officeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Offices", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            officeName = "Main Office"
                        },
                        new
                        {
                            Id = 2,
                            officeName = "Branch Office"
                        },
                        new
                        {
                            Id = 3,
                            officeName = "Remote Office"
                        },
                        new
                        {
                            Id = 4,
                            officeName = "Headquarters"
                        },
                        new
                        {
                            Id = 5,
                            officeName = "Satellite Office"
                        });
                });

            modelBuilder.Entity("_10_Code_first.Entites.Instructor", b =>
                {
                    b.HasOne("_10_Code_first.Entites.Office", null)
                        .WithOne("instructor")
                        .HasForeignKey("_10_Code_first.Entites.Instructor", "OfficeId");
                });

            modelBuilder.Entity("_10_Code_first.Entites.Office", b =>
                {
                    b.Navigation("instructor");
                });
#pragma warning restore 612, 618
        }
    }
}
