// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _10_Code_first.Data;

#nullable disable

namespace _10_Code_first.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260214221004_AddSectionSchedule")]
    partial class AddSectionSchedule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_10_Code_first.Entites.Course", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<decimal>("Price")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Courses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseName = "Mathmatics",
                            Price = 1000m,
                            Tag = "BEGINNER"
                        },
                        new
                        {
                            Id = 2,
                            CourseName = "Physics",
                            Price = 2000m,
                            Tag = "ADVANCED"
                        },
                        new
                        {
                            Id = 3,
                            CourseName = "Chemistry",
                            Price = 1500m,
                            Tag = "INTERMEDIATE"
                        },
                        new
                        {
                            Id = 4,
                            CourseName = "Biology",
                            Price = 1200m,
                            Tag = "BEGINNER"
                        },
                        new
                        {
                            Id = 5,
                            CourseName = "CS-50",
                            Price = 3000m,
                            Tag = "ADVANCED"
                        });
                });

            modelBuilder.Entity("_10_Code_first.Entites.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<int?>("OfficeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId")
                        .IsUnique()
                        .HasFilter("[OfficeId] IS NOT NULL");

                    b.ToTable("Instructors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Ahmed",
                            LastName = "Abdullah",
                            OfficeId = 1
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Yasmeen",
                            LastName = "Yasmeen",
                            OfficeId = 2
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Khalid",
                            LastName = "Hassan",
                            OfficeId = 3
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Nadia",
                            LastName = "Ali",
                            OfficeId = 4
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Ahmed",
                            LastName = "Abdallah",
                            OfficeId = 5
                        });
                });

            modelBuilder.Entity("_10_Code_first.Entites.Office", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("officeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Offices", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            officeName = "Main Office"
                        },
                        new
                        {
                            Id = 2,
                            officeName = "Branch Office"
                        },
                        new
                        {
                            Id = 3,
                            officeName = "Remote Office"
                        },
                        new
                        {
                            Id = 4,
                            officeName = "Headquarters"
                        },
                        new
                        {
                            Id = 5,
                            officeName = "Satellite Office"
                        });
                });

            modelBuilder.Entity("_10_Code_first.Entites.Section", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int?>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Sections", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            InstructorId = 1,
                            SectionName = "S_MA1"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            InstructorId = 2,
                            SectionName = "S_MA2"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 2,
                            InstructorId = 1,
                            SectionName = "S_PH1"
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 2,
                            InstructorId = 3,
                            SectionName = "S_PH2"
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 3,
                            InstructorId = 2,
                            SectionName = "S_CH1"
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 3,
                            InstructorId = 3,
                            SectionName = "S_CH2"
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 4,
                            InstructorId = 4,
                            SectionName = "S_BI1"
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 4,
                            InstructorId = 5,
                            SectionName = "S_BI2"
                        },
                        new
                        {
                            Id = 9,
                            CourseId = 5,
                            InstructorId = 4,
                            SectionName = "S_CS1"
                        },
                        new
                        {
                            Id = 10,
                            CourseId = 5,
                            InstructorId = 5,
                            SectionName = "S_CS2"
                        },
                        new
                        {
                            Id = 11,
                            CourseId = 5,
                            InstructorId = 4,
                            SectionName = "S_CS3"
                        });
                });

            modelBuilder.Entity("_10_Code_first.Entites.Instructor", b =>
                {
                    b.HasOne("_10_Code_first.Entites.Office", null)
                        .WithOne("instructor")
                        .HasForeignKey("_10_Code_first.Entites.Instructor", "OfficeId");

                    b.OwnsOne("_10_Code_first.Entites.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<int>("InstructorId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("Address_City");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("Address_Street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("Address_ZipCode");

                            b1.HasKey("InstructorId");

                            b1.ToTable("Instructors");

                            b1.WithOwner()
                                .HasForeignKey("InstructorId");

                            b1.HasData(
                                new
                                {
                                    InstructorId = 1,
                                    City = "Cairo",
                                    Street = "123 Main St",
                                    ZipCode = "11511"
                                },
                                new
                                {
                                    InstructorId = 2,
                                    City = "Alexandria",
                                    Street = "456 Elm Ave",
                                    ZipCode = "21500"
                                },
                                new
                                {
                                    InstructorId = 3,
                                    City = "Cairo",
                                    Street = "789 Oak Blvd",
                                    ZipCode = "11765"
                                });
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("_10_Code_first.Entites.Section", b =>
                {
                    b.HasOne("_10_Code_first.Entites.Course", null)
                        .WithMany("Sections")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_10_Code_first.Entites.Instructor", null)
                        .WithMany("Sections")
                        .HasForeignKey("InstructorId");

                    b.OwnsOne("_10_Code_first.Entites.ValueObjects.DateRange", "Schedule", b1 =>
                        {
                            b1.Property<int>("SectionId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("Schedule_EndDate");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("Schedule_StartDate");

                            b1.HasKey("SectionId");

                            b1.ToTable("Sections");

                            b1.WithOwner()
                                .HasForeignKey("SectionId");

                            b1.HasData(
                                new
                                {
                                    SectionId = 1,
                                    EndDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                                    StartDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                                },
                                new
                                {
                                    SectionId = 2,
                                    EndDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                                    StartDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                                },
                                new
                                {
                                    SectionId = 3,
                                    EndDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                                    StartDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                                },
                                new
                                {
                                    SectionId = 4,
                                    EndDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                                    StartDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                                },
                                new
                                {
                                    SectionId = 5,
                                    EndDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                                    StartDate = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                                },
                                new
                                {
                                    SectionId = 6,
                                    EndDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                                    StartDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                                },
                                new
                                {
                                    SectionId = 7,
                                    EndDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                                    StartDate = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                                },
                                new
                                {
                                    SectionId = 8,
                                    EndDate = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                                    StartDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                                },
                                new
                                {
                                    SectionId = 9,
                                    EndDate = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                                    StartDate = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                                },
                                new
                                {
                                    SectionId = 10,
                                    EndDate = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                                    StartDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                                },
                                new
                                {
                                    SectionId = 11,
                                    EndDate = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                                    StartDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                                });
                        });

                    b.Navigation("Schedule")
                        .IsRequired();
                });

            modelBuilder.Entity("_10_Code_first.Entites.Course", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("_10_Code_first.Entites.Instructor", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("_10_Code_first.Entites.Office", b =>
                {
                    b.Navigation("instructor");
                });
#pragma warning restore 612, 618
        }
    }
}
